# TCL File Generated by Component Editor 16.1
# Sat May 18 16:56:45 CEST 2019
# DO NOT MODIFY


# 
# ws2812b_dma "ws2812b_dma" v1.0
# Joost Hartkamp 2019.05.18.16:56:45
# adressable led dma reader
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ws2812b_dma
# 
set_module_property DESCRIPTION "adressable led dma reader"
set_module_property NAME ws2812b_dma
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP customblocks
set_module_property AUTHOR "Joost Hartkamp"
set_module_property DISPLAY_NAME ws2812b_dma
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ws2812b_dma
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file WS2812B_DMA.vhd VHDL PATH WS2812B_DMA.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter numleds INTEGER 5
set_parameter_property numleds DEFAULT_VALUE 5
set_parameter_property numleds DISPLAY_NAME numleds
set_parameter_property numleds TYPE INTEGER
set_parameter_property numleds UNITS None
set_parameter_property numleds ALLOWED_RANGES -2147483648:2147483647
set_parameter_property numleds HDL_PARAMETER true
add_parameter base INTEGER 0 ""
set_parameter_property base DEFAULT_VALUE 0
set_parameter_property base DISPLAY_NAME base
set_parameter_property base WIDTH ""
set_parameter_property base TYPE INTEGER
set_parameter_property base UNITS None
set_parameter_property base ALLOWED_RANGES -2147483648:2147483647
set_parameter_property base DESCRIPTION ""
set_parameter_property base HDL_PARAMETER true
add_parameter returnticks INTEGER 4000
set_parameter_property returnticks DEFAULT_VALUE 4000
set_parameter_property returnticks DISPLAY_NAME returnticks
set_parameter_property returnticks TYPE INTEGER
set_parameter_property returnticks UNITS None
set_parameter_property returnticks ALLOWED_RANGES -2147483648:2147483647
set_parameter_property returnticks HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_dma_master
# 
add_interface avalon_dma_master avalon start
set_interface_property avalon_dma_master addressUnits SYMBOLS
set_interface_property avalon_dma_master associatedClock clock
set_interface_property avalon_dma_master associatedReset reset
set_interface_property avalon_dma_master bitsPerSymbol 8
set_interface_property avalon_dma_master burstOnBurstBoundariesOnly false
set_interface_property avalon_dma_master burstcountUnits WORDS
set_interface_property avalon_dma_master doStreamReads false
set_interface_property avalon_dma_master doStreamWrites false
set_interface_property avalon_dma_master holdTime 0
set_interface_property avalon_dma_master linewrapBursts false
set_interface_property avalon_dma_master maximumPendingReadTransactions 0
set_interface_property avalon_dma_master maximumPendingWriteTransactions 0
set_interface_property avalon_dma_master readLatency 0
set_interface_property avalon_dma_master readWaitTime 1
set_interface_property avalon_dma_master setupTime 0
set_interface_property avalon_dma_master timingUnits Cycles
set_interface_property avalon_dma_master writeWaitTime 0
set_interface_property avalon_dma_master ENABLED true
set_interface_property avalon_dma_master EXPORT_OF ""
set_interface_property avalon_dma_master PORT_NAME_MAP ""
set_interface_property avalon_dma_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_dma_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_dma_master waitrequest waitrequest Input 1
add_interface_port avalon_dma_master address address Output 32
add_interface_port avalon_dma_master read read Output 1
add_interface_port avalon_dma_master readdata readdata Input 32


# 
# connection point led_clock
# 
add_interface led_clock clock end
set_interface_property led_clock clockRate 20000000
set_interface_property led_clock ENABLED true
set_interface_property led_clock EXPORT_OF ""
set_interface_property led_clock PORT_NAME_MAP ""
set_interface_property led_clock CMSIS_SVD_VARIABLES ""
set_interface_property led_clock SVD_ADDRESS_GROUP ""

add_interface_port led_clock ledclk clk Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit ledout adressable_led_data Output 1

